# Mix

In [5]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

import numpy as np
import matplotlib.pyplot as plt

from scipy import ndimage 

import os
import cv2
import pandas as pd
%matplotlib inline

In [6]:
#Load the coordinates data set
df = pd.read_csv('train.csv')

In [7]:
# Load images and resize 
root= './train'
names = []
train_crude = []
for file in os.listdir(root):
    img = cv2.imread(os.path.join(root, file))#,cv2.IMREAD_GRAYSCALE)
    img = cv2.resize(img, (img.shape[1]//3,img.shape[0]//3))
    train_crude.append(img)
    names.append(file.split('.')[0])
    
data = np.stack( train_crude, axis=0 )

### Extract feature CNN

In [ ]:
tf.__version__

In [8]:
from tensorflow.keras.applications.resnet_v2 import preprocess_input, decode_predictions
from tensorflow.keras.applications.resnet_v2 import ResNet50V2
base_model = ResNet50V2(weights='imagenet',input_shape=[163, 226,3],include_top=False)

In [9]:
#get features in batches and flatten
feat = []
for i in range(0,7500,500):
    temp = base_model.predict(preprocess_input(data[i:i+500]))
    feat.append(temp)
    

feat0 = np.concatenate(feat, axis=0) 
feat2 = [i.ravel() for i in feat0]
feat2 = np.stack(feat2, axis=0) #these are the features

In [8]:
feat2.shape

(7500, 98304)

### Nearest neighbor

In [10]:

from sklearn.neighbors import NearestNeighbors
train = feat2[:7000]
validation = feat2[7000:]

neighTest = NearestNeighbors(n_neighbors=5)
neighTest.fit(train)

predictions = neighTest.kneighbors(validation)

In [39]:
predictions[0][0] # Distances

array([437.69397, 452.00183, 455.92117, 459.7137 , 459.8171 ],
      dtype=float32)

In [40]:
predictions[1][0] # Indices

array([2964,  684,  322, 3702, 6431], dtype=int64)

In [ ]:
plt.subplots(figsize=(15,15))
for ix,im in enumerate(predictions):
    toShow = data[im]
    plt.subplot(1,6,ix+1)
    plt.imshow(toShow, cmap='gray')  
    plt.title(im)
    plt.axis('off')
plt.show()

### SIFT

In [11]:
sift = cv2.SIFT_create()

#Generates de key points and descriptors of the neighbours of the images to be predicted

key_points=[]
descript=[]
for  i, i_n in enumerate(predictions[1]): #Iterate over indices of predictions
    # print(i_n)
    kp_neighbours=[]
    desc_neighbours=[]
    for neigh in i_n: # Iterates over the indices of the k nearest neighbours of the instance being predicted
        neighbour=data[neigh] # A neighbour of the instances being predicted
        kp, des = sift.detectAndCompute(neighbour,None) # key points and descriptors of the neighbour of instance being predicted
        kp_neighbours.append(kp)
        desc_neighbours.append(des)
        
    key_points.append(kp_neighbours)
    descript.append(desc_neighbours)



In [122]:
len(descript[0]) #[0][0]

5

In [12]:
#Generates de key points and descriptors of the images to be predicted

validation_img=data[7000:]

key_points_dev=[]
descript_dev=[]

for  img in validation_img: #Iterate over indices of predictions
    # print(i_n)
    kp, des = sift.detectAndCompute(img,None) # key points and descriptors of the instance being predicted
    key_points_dev.append(kp)
    descript_dev.append(des)
    
#descript_dev=np.array(descript_dev)

In [13]:
len(descript_dev[0][0])

128

In [18]:
def find_matches(matcher,des1, des2):
    # Matching descriptor using KNN algorithm
    # print(des1,'\n')
    # print(des2)
    try:
        matches = matcher.knnMatch(des1,des2,k=2)
    except:
        return None

    # Store all good matches as per Lowe's Ratio test.
    ratio = 0.6
    good = []
    for m,n in matches:
        if m.distance < ratio*n.distance:
            good.append(m)
    return len(good)

def match(desc_list1, desc_list2):
    
    # FLANN parameters and initialize
    FLANN_INDEX_KDTREE = 1
    index_params = dict(algorithm = FLANN_INDEX_KDTREE, trees = 5)
    search_params = dict(checks=50)   # or pass empty dictionary
    flann = cv2.FlannBasedMatcher(index_params,search_params)
    
    best_neighbours_matched=[]
    for i, desc1 in enumerate(desc_list1):
        # print('\n\n')
        # print('image {}'.format(i))
        matches_list=[]
        ind_neighbour=[]
        for j, desc2 in enumerate(desc_list2[i]):
            #print(j)
            if desc2 is not None:
                #print('neighb {}'.format(j))
                n_matches = find_matches(flann, desc1, desc2)
                if n_matches is not None:
                    ind_neighbour.append(predictions[1][i][j]) #Appends index in the data of the neighbour from the image being predicted
                    matches_list.append(n_matches) #Appends matches between the current neighbour and the instance being predicted
                else:
                    continue
        
        #print('len ind neigh',ind_neighbour)
        #print('len matches list',matches_list)
        neighb_matches=np.stack([ind_neighbour,matches_list],axis=1) #Creates numpy array. Rows are descriptors of different neighbours. 
                                                                     # First column is index in the data, Second column is how many matches that neighbour has with the current instance
        neighb_matches=neighb_matches[neighb_matches[:, 1].argsort()[::-1][:len(matches_list)]]  #Sorts array in descending order, more matches on top and less matches at the bottom :5 is the number of neighbours
        #print(neighb_matches)
        best_neighbours_matched.append(neighb_matches)
    
    return best_neighbours_matched
                                 
k_best_matches=match(descript_dev,descript)

In [25]:
k_best_matches

array([[4436,    6],
       [ 217,    2]], dtype=int64)